### ISSUE TITLE
Add exports for fuel tank optimization and fuel tank volume talents.

### ISSUE THREAD

**Issue by d6rks1lv3rz3r0** [DorianTheGrey/DU-DamageReport#10]

**Comment by d6rks1lv3rz3r0** [comment]
Neverminded the handlings are there. Only the optimization is needed.

**Comment by DorianTheGrey** [comment]
Hi there, I am not aware theres a "fuel tank optimization" in the game? Maybe I am missing something, can you point me to it? I only know about fuel tank handling and fuel efficiency, and those are both in there for all three types. Can you elaborate please?

**Comment by d6rks1lv3rz3r0** [comment]
Inventory -> Stock Control -> Fuel Tank Optimization

**Comment by DorianTheGrey** [comment]
You are right, Sir, and I am blind. :D Thanks a lot, got added to the to do list. :)

**Comment by DorianTheGrey** [comment]
Fixed in v3.04. Please set your skills in the lua parameters (they moved away from the settings page).
