### ISSUE TITLE
Rocket Fuel Talent Increments.

### ISSUE THREAD

**Issue by Musclethorpe** [DorianTheGrey/DU-DamageReport#13]
Heya, awesome upgrades to the script, and thanks for all the hard work.

The one thing I noticed is that it appears the LUA Rocket Fuel Handling talents scale in increments of 20%, like the other tank handling talents, but they actually increase by 10% per rank. For me to accurately reflect my Rank 4 tank handling (+40%), I have to set the LUA parameters to Rank 2.

**Comment by DorianTheGrey** [comment]
Thanks Musclethorpe, when I am back I ll fix it. (Currently taking a break.)
