### ISSUE TITLE
new view: required scraps & time to repair

### ISSUE THREAD

**Issue by kgersen** [DorianTheGrey/DU-DamageReport#9]
if possible a new view mode (toggle somewhere to switch view mode like 'sim') to replace 'health' and 'damage' columns with 'required scraps amount' and 'time to repair' (lua parameter to set the scrap tier or T1/T2/T3/T4 buttons on top of the view). 
On header row: the total required scraps & time to repair
For talent modifiers do same as scrap tier (parameter or buttons) (unless lua can request player talents ?)

**Comment by DorianTheGrey** [comment]
Done in version 3.0 :)
